### PR TITLE
[Fix] Circle Ci

### PR DESCRIPTION
**Pull request by adhinneupane**

### CODE REVIEW

**Comment by adhinneupane** [comment]
@mcopik looks like some test's are failing for CI.

**Comment by mcopik** [comment]
Dear @adhinneupane, thanks for the PR! It is much appreciated :-)

So it happens that we resolved the issue shortly before your contribution on the `dev` branch - the primary issues of the CI were the missing dependency on the YAML types and the `docker` directory that overshadows the package. The latter issue is a much larger one, and thus I have to push the #112 PR.

Nevertheless, I noticed an additional change with docker volume - can you clarify why it is needed? The AWS test is temporarily disabled but I will be happy to merge for future use :-)

**Comment by mcopik** [comment]
@adhinneupane Hi! Do you think it still addresses the CI issue?

**Comment by mcopik** [comment]
Closing down due to lack of activity.

**Pull request closed without merging**
